version: 1.0.{build}
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: 4GEc9+zwnC3QqpeTKzuVgzODZWveBtiB3j9X1fe+H8IWeRyEtG47BKAV0j6ne69p
install:
- ps: >-
    $project = Get-Content ./src/Stubble.Extensions.Loaders/project.json -Raw | ConvertFrom-Json;
    $version = Get-Content ./src/Stubble.Extensions.Loaders/version.json -Raw | ConvertFrom-Json;
    $ci_version = $project.version.Split('-')[0] + "." + $env:APPVEYOR_BUILD_NUMBER;
    Update-AppveyorBuild -Version $ci_version;
    if($version.packagePostfix) {
        $env:verion_suffix=$version.packagePostfix;
    }
    dotnet --info
before_build:
- ps: dotnet restore .\src\Stubble.Extensions.Loaders\
- ps: dotnet restore .\test\Stubble.Extensions.Loaders.Tests\
build_script:
- ps: dotnet --verbose build .\src\Stubble.Extensions.Loaders\ -c Release
after_test:
- ps: >-
    if($env:verion_suffix) {
        dotnet --verbose pack .\src\Stubble.Extensions.Loaders\ -o .\out --version-suffix $env:verion_suffix
    } else {
        dotnet --verbose pack .\src\Stubble.Extensions.Loaders\ -o .\out
    }
test_script:
- ps: >-
    $Package_Locations = $env:USERPROFILE + "\.nuget\packages";
    $OpenCover_Location = Get-ChildItem ($Package_Locations + "\OpenCover*\*\tools") | Select-Object -First 1 -ExpandProperty FullName;
    $CoverallsNet_Location = Get-ChildItem ($Package_Locations + "\coveralls.net\*\tools") | Select-Object -First 1 -ExpandProperty FullName;

    Push-Location .\test\Stubble.Extensions.Loaders.Tests\

    $openCoverExe = "$OpenCover_Location\OpenCover.Console.exe -register:user -target:""dotnet.exe"" ""-targetargs:test --framework netcoreapp1.0 -appveyor"" -filter:""+[Stubble.*]*"" -skipautoprops -output:coverage.xml";
    $coverallsExe = "$CoverallsNet_Location\csmacnz.Coveralls.exe --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage ""$env:APPVEYOR_REPO_COMMIT_MESSAGE"" --jobId $env:APPVEYOR_JOB_ID";

    iex $openCoverExe;
    Write-Host "Running Coveralls";
    iex $coverallsExe;

    Pop-Location;
artifacts:
- path: .\out\*.nupkg
- path: .\test\Stubble.Extensions.Loaders.Tests\coverage.xml
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    APPVEYOR_REPO_TAG: true
