version: 1.0.1000000.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: 4GEc9+zwnC3QqpeTKzuVgzODZWveBtiB3j9X1fe+H8IWeRyEtG47BKAV0j6ne69p
  CODECOV_REPO_TOKEN:
    secure: Bh0IR5gAAePAQsaMKjQ4NeLUbAjfDzg8dr4vJDqgyVZcNGXlI2fQUUjcnBoRX8du
install:
- ps: >-
    dotnet --info
build_script:
- ps: .\build.ps1 -Target Appveyor
artifacts:
- path: .\artifacts\*.nupkg
- path: .\coverage-results\*
test: off
deploy:
- provider: NuGet
  api_key:
    secure: EMoHTW3rc1OUCEnrICn6gxCbaT8a3HSkedN6mbHqOzo1KHQodR13frz6FZwQuweE
  on:
    APPVEYOR_REPO_TAG: true
